### ISSUE TITLE
New Steam client causes crash on invite

### ISSUE THREAD

**Issue by Physikbuddha** [m4dEngi/RemotePlayWhatever#103]
On Windows, using the latest version 0.2.3 of RemotePlayWhatever, the program crashes without any message when I try to send a Remote Play invitation to a friend. This was still working fine two days ago with the old Steam client.

Friend list is appearing fine, only the invitation part seems to be broken.

**Comment by nanotechnician** [comment]
Can confirm, new steam client update which was the one used in beta (and now stable release).

**Comment by m4dEngi** [comment]
Working on a fix.

**Comment by m4dEngi** [comment]
Should be fixed with latest release.
