### ISSUE TITLE
Option to change Spacewar game with any other ID

### ISSUE THREAD

**Issue by Derfas13** [m4dEngi/RemotePlayWhatever#105]
Please add an option to change Spacewar game with any other ID.

Spacewar doesn't support gamepads, so when you use it for non-steam games, you can't use gamepads.

If i could've in my life figure out how to cmake anything, i would do it myself by editing source.

**Comment by Derfas13** [comment]
Update:

Changing game ID in 2 .cpp files doesn't change issue with gamepads :\

- Used game changes from Spacewar to selected one;
- Steam games without remote play work and do have gamepads;
- Non-Steam games works but don't have gamepads :c

Before last Steam update we didn't use RemotePlayWhatever for Non-Steam games.
Instead we used steam_appid file trick.
But after last Steam update this way still works, but it leaves a permanent window on top of players screen. Which we can't remove.

**Comment by Derfas13** [comment]
Update 2:

Using game folder wipe method instead of steam_appid file doesn't change issue with permanent window on top of client screen :c

**Comment by m4dEngi** [comment]
Yes, it's not just the ID. You can already change it to any valid AppID using the `--appid` command line argument. However, to make the controllers work as expected for non-Steam games, it is necessary to initialize the SteamAPI under the same PID, which is not possible without messing with the original game/steam executables, unless we provide it with the appropriate steam_appid.txt file and hope that the in-game overlay will do it for us.

**Comment by Derfas13** [comment]
Well, seems like they added some checks, so steam_appid.txt and messing with the original game folder don't let clients to get controls.

It looks like if Steam overlay doesn't recognize game window as active anymore in some weird way. Unless it is really the window of Steam game and used AppID. But it doesn't break RemotePlayWhatever,  i suppose because you are making it as m_enabledDesktopStreaming.

**Comment by Derfas13** [comment]
Somehow it doesn't work in any supported game anymore. Even though we tested it recently, and it did work.

So it is not meant to be a fix for non-steam games use. But just a broken Steam update.

Case closed.
