### ISSUE TITLE
new Steam client UI/overlay causes the app do dysfunction

### ISSUE THREAD

**Issue by ShinySunlight** [m4dEngi/RemotePlayWhatever#106]
Trying to start a remote play session with the new Steam UI, which released on the live build a week or two ago, will just cause the app to crash and fail to create the session

**Comment by m4dEngi** [comment]
Sorry, the readme is a bit outdated, the latest RPW version only supports the latest stable steam client. No plans to support beta client branch atm.

**Comment by ShinySunlight** [comment]
The new UI is on the live branch now, which is why I made the post

**Comment by m4dEngi** [comment]
RPW 0.2.4 seem to work fine with the latest stable desktop client version on my end. What's your client version and OS?
