### ISSUE TITLE
RPW 0.2.4 seem Not to work

### ISSUE THREAD

**Issue by zockerdirk** [m4dEngi/RemotePlayWhatever#108]
Hi, we have a Problem with the new 0.2.4 Update. We could Split our Monitor but not mouse and keyboard?
What is the issue?
thanks for your help.

**Comment by m4dEngi** [comment]
It should bring up Remote Play Together overlay on remote play session start where you can assign controls or enable shared keyboard/mouse input (under guests name). 

Shared input for keyboard and mouse is disabled by default.

**Comment by zockerdirk** [comment]
Thanks a lot ...might sending a Screenshot where to find that in the steam menu?Von meinem iPhone gesendetAm 04.07.2023 um 11:43 schrieb Dmitry ***@***.***>:﻿
It should bring up Remote Play Together overlay on remote play session start where you can assign controls or enable shared keyboard/mouse input (under guests name).
Shared input for keyboard and mouse is disabled by default.

**Comment by DriftWare07** [comment]
I can get it to work with steam games, but it doesn't detect non steam games even if they are added to your library via 'Add non-steam game'. How does this work?

**Comment by Rogus** [comment]
> I can get it to work with steam games, but it doesn't detect non steam games even if they are added to your library via 'Add non-steam game'. How does this work?


Try at reddit they have a subreddit in emulators teaching how to workaround the limitations or you could use remoteplaydetached and put a donor game it's a free game and you need to rename and exclude some archives from the game.

**Comment by zockerdirk** [comment]
Hallo,
Eventuell gibt es dafür eine Lösung?





Von meinem iPhone gesendet
