### ISSUE TITLE
Simply dont work

### ISSUE THREAD

**Issue by Milor123** [m4dEngi/RemotePlayWhatever#11]
Try execute the RemotePlayWhatever.exe as administrator, the steam, move in diferences directories, but not work in non-steam games. Steam detect the game but the remote invite dont show in steam

What should I do?

**Comment by m4dEngi** [comment]
Are you in steam client beta?

**Comment by Milor123** [comment]
> 
> 
> Are you in steam client beta?

Ohhh yes, its true, I've disable beta, and reinstall normal steam.
Now it works!!! Thank you very much
Problem Solved!
