### ISSUE TITLE
Can't launch the app image on opensuse tumbleweed

### ISSUE THREAD

**Issue by TheAnnoyingFruit** [m4dEngi/RemotePlayWhatever#111]
This is what I get when trying to run the app image :
(remoteplaywhatever:27607): Gtk-WARNING **: 02:29:51.788: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/scalable/status/image-missing.svg: Unable to load image-loading module: libpixbufloader-svg.so: libpixbufloader-svg.so: cannot open shared object file: No such file or directory (gdk-pixbuf-error-quark, 5)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/scalable/status/image-missing.svg: Unable to load image-loading module: libpixbufloader-svg.so: libpixbufloader-svg.so: cannot open shared object file: No such file or directory (gdk-pixbuf-error-quark, 5)
Aborted (core dumped)
This is what I get when trying to run the app image with sudo :
Error: Unable to initialize GTK+, is DISPLAY set properly?

**Comment by TheAnnoyingFruit** [comment]
Also based on a similar issue already raised is this compatible with the steam flatpak? That may be the issue since I don't use the native rpm package.

**Comment by m4dEngi** [comment]
No, it's not compatible with flatpak version of steam. And it needs somewhat direct access to running client instance to function.

**Comment by owowouwu** [comment]
@TheAnnoyingFruit Did you get it working with the rpm version of steam? I'm on Fedora 37 and I still get that error with the rpm version.

**Comment by TheAnnoyingFruit** [comment]
I haven't tried it because I have dependency issues with the rpm version of steam and much prefer the flatpak. I.e. gmod and tf2

**Comment by TheAnnoyingFruit** [comment]
I will try it when I get the chance

**Comment by TheAnnoyingFruit** [comment]
> @TheAnnoyingFruit Did you get it working with the rpm version of steam? I'm on Fedora 37 and I still get that error with the rpm version.

Ok upon installing the rpm version of steam on tumbleweed it now works. Once I close steam and try to open it, the error messages return. So I can confirm for me it was using the flatpak version of steam that caused the issue.

**Comment by TheAnnoyingFruit** [comment]
@m4dEngi I would like to request that you add that the app does not work with the flatpak version of steam to the read me.
