### ISSUE TITLE
Won't Open

### ISSUE THREAD

**Issue by HaziiHere** [m4dEngi/RemotePlayWhatever#116]
im trying to play 2 player pizza tower with a friend, but the app to remote play wont open. i've tried run as admin but it won't work

**Comment by m4dEngi** [comment]
What OS, version of Steam and RPW are you using?

**Comment by Phobobobo** [comment]
Having the same problem. I am on the newest beta relese of steam.

**Comment by Phobobobo** [comment]
So i tried to downgrade to the regular Steam version, and RPW works with that, but unfortunately this version has a bug with the D-pad that getes fixed in the beta version. Would be nice if you could update so it works with the beta. thanks
