### ISSUE TITLE
Won't Open

### ISSUE THREAD

**Issue by ivanapr** [m4dEngi/RemotePlayWhatever#117]
Hi! I'm trying to play Tales of Arise with friends. On Steam the RPW app tries to run but won't open :(
Win 10.
Steam version 1694466342 
RPW version 0.2.4-alpha
Thanks!

**Comment by henzloid** [comment]
same here, i use it 3am in the morning and now can't open...

**Comment by VanKhron** [comment]
Yeah, not working for me either, seems incompatible with the latest steam version.

**Comment by Vistalgia** [comment]
Not working for my friend either.
