### ISSUE TITLE
steam update problem 

### ISSUE THREAD

**Issue by RebelDima** [m4dEngi/RemotePlayWhatever#146]
after another steam update, program just crashing

**Comment by mintwzy** [comment]
I updated some information in another issue [here](https://github.com/m4dEngi/RemotePlayWhatever/issues/145#issuecomment-2169886250).

**Comment by TkMatt** [comment]
Yep, program crashes and doesnt create/sends invites. Im using this a lot lately, it's an amazing work!

**Comment by m4dEngi** [comment]
#145
