### ISSUE TITLE
No input using Non-Steam game.

### ISSUE THREAD

**Issue by UwUo-oUwU** [m4dEngi/RemotePlayWhatever#150]
Using RemotePlayWhatever 0.2.7. The controller displays in the controller options of Ryujinx, but no input into the game/binding settings. I am unable to disable Steam Input for their controller as well under the controller option of Steam as it sees it unsupported yet I can do it for mine. Unsure if this is a Steam Client issue or not. Can test if requested.

**Comment by crudyy** [comment]
You can try adding RPW as a non-steam game, and then under its launch options, add "--appid 0". This might fix the input issues.

**Comment by UwUo-oUwU** [comment]
> You can try adding RPW as a non-steam game, and then under its launch options, add "--appid 0". This might fix the input issues.

Thank you so much! This seems to have fixed it, @m4dEngi would you be able to make a note of this on the READ ME for others that may encounter this issue?
