### ISSUE TITLE
It ends without invitation.

### ISSUE THREAD

**Issue by Solfi321** [m4dEngi/RemotePlayWhatever#151]
If I select generate link or select the friend's icon, the app closes after a few seconds and no invitation is generated.

**Comment by crudyy** [comment]
Did you update RPW to 0.2.7?

**Comment by Solfi321** [comment]
Sorry, I replaced it with the latest version and was able to share it. 0.2.6 version did not work for me for some reason and only my friend who asked me to verify it was able to use it.
