### ISSUE TITLE
The Remote Play Together Tab to manage controls and give permissions for controls won't show up after inviting friend. 

### ISSUE THREAD

**Issue by C4RTYP4NTS** [m4dEngi/RemotePlayWhatever#159]
![image_2024-07-22_154553010](https://github.com/user-attachments/assets/671e8b6f-7bb7-4b36-9f7d-bde63cf60837)
This menu won't show up and I cant find it anywhere. How do you fix this?

**Comment by Thorium0** [comment]
This is a clone of #152 . The only workaround I could find is using big picture mode and pressing ctrl+2 to open the menu.

**Comment by m4dEngi** [comment]
#152
