### ISSUE TITLE
No Remote Play Together tab in steam overlay

### ISSUE THREAD

**Issue by ZeeWanderer** [m4dEngi/RemotePlayWhatever#162]
This is happening on latest mainline Steam Client.

Invites are sent correctly and people can join and receive video feed however the UI tab that allows to enable input for connected players is simply missing. It does not appear as it did before on first invite sent and its missing from the available tabs list at the bottom of the screen. The workaround is for other players to connect gamepad after joining as it's enabled by default. But using keyboard/mouse currently seems to be impossible.

**Comment by MorningKek** [comment]
Same here. Can't play anything with a friend who doesn't have a gamepad

**Comment by Evidark** [comment]
+

**Comment by wew-gamedev** [comment]
Bugged for me as well
