### ISSUE TITLE
When inviting my friend program closes

### ISSUE THREAD

**Issue by Pelimies1234** [m4dEngi/RemotePlayWhatever#170]
I was fine like 5 days ago, but now the program closes as soon as I try to invite my friend to play, I have tried different solutions for this myself but they doesn't work, if you would have any ideas how to get it working again, I would appreciate it, thank you and have a nice day!

**Comment by m4dEngi** [comment]
Check for steam client updates. If you're on the beta branch, switch to stable client.

**Comment by Pelimies1234** [comment]
I reinstalled Remote Play Whatever and it worked, I saw few guys stating that it wont work but it worked for me. Thank you anyway for your quick response
