### ISSUE TITLE
Steam Deck Remoteplaywhatever doesn't load at all

### ISSUE THREAD

**Issue by xav07theboi** [m4dEngi/RemotePlayWhatever#171]
when i load the appImage (0.2.8) the ui that normally pops up doesn't appear and even in big picture then remoteplaytogether doesn't appear anymore

**Comment by Victor-Silva-3000** [comment]
Same here.

I got the the terminal output for it:

/tmp/.mount_RemoteAOX8Ly/usr/bin/remoteplaywhatever: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /tmp/.mount_RemoteAOX8Ly/usr/bin/remoteplaywhatever)

**Comment by santumerino** [comment]
I have the same issue, with the same terminal output as mentioned above. It might be relevant to mention I'm running Linux Mint 21.3 (virginia) on X11.

**Comment by DaHitManN** [comment]
Similarly I am going through the same error in SteamOS. We share the same output in Konsole/Terminal as well. Maybe we have to install some dependencies to fix that.

**Comment by Victor-Silva-3000** [comment]
Weird, I thought it would be related to SteamOS only...

I may be missing something here, but aren't AppImages supposed to have all their dependencies packaged alongside their executables? It seems to be trying to access a dependency out of the sandbox...

Please, do correct me if i'm wrong :)

**Comment by DaHitManN** [comment]
As a Linux noob, I didn’t know the AppImages are supposed to have all
dependencies bundled. With that in mind, I am more than certain that it’s
accessing some other dependency, GLIBCXX_3.4.32.

**Comment by Victor-Silva-3000** [comment]
Yeah, like Flatpaks or Snaps they are meant to solve dependency problems that can happen when a software relies on a dependency that may not be available on your distribution repository or available but with a different version.

I _think_ in this case there was an issue packaging the library for the latest build... Forgot to include it maybe? :P

In any case I hope it gets fixed soon, me and my buddy are playing through Silent Hill 4 using this tool and I really want to get back into it!

**Comment by m4dEngi** [comment]
Re-uploaded AppImage build.

**Comment by xav07theboi** [comment]
k i will check it

**Comment by xav07theboi** [comment]
it works
