### ISSUE TITLE
No sound in remote play.

### ISSUE THREAD

**Issue by KOTOKZ7** [m4dEngi/RemotePlayWhatever#177]
No sound. I tested it with two people, today the stream of any sound in the application disappeared.

**Comment by KateReller** [comment]
Can confirm issue exists.

**Comment by vanyassia** [comment]
Same problem

**Comment by Eddieeeeeeeeeeee** [comment]
I found a solution for some games not transmitting the sound.
For me, the problem laid in the "Microsoft Spacial Sound" setting.

To fix it, deactivate spacial sound and you should be good to go.

**Comment by Eddieeeeeeeeeeee** [comment]
Addition: I had to deactivate it INSIDE THE GAME!
Not in windows! (Tested it for Uncharted 4 and Ori and the WIll of the Wisps).

**Comment by feffom** [comment]
No sound here either, Spatial sound unabled on windows, and no option to it ingame.

**Comment by KOTOKZ7** [comment]
The solution to this problem is to install the beta version of Steam with a new update and fix.

In the Steam client, click on Steam in the top left corner, then select the Settings menu. Open the "Interface" tab and click on the drop-down menu in the "Participation in the beta testing of the Steam client" section. Select the Steam Beta Update option. You will be prompted to restart Steam.

**Comment by foxing-quietly** [comment]
> The solution to this problem is to install the beta version of Steam with a new update and fix.
> 
> In the Steam client, click on Steam in the top left corner, then select the Settings menu. Open the "Interface" tab and click on the drop-down menu in the "Participation in the beta testing of the Steam client" section. Select the Steam Beta Update option. You will be prompted to restart Steam.

I'm afraid this issue was closed in error. I just re-tested using the beta Steam update on both my Steam Deck and PC. I have no sound in the steam deck menu during streaming. I do have sound when opening up a Proton and Linux native game from Steam (Subnautica and Artic Eggs). I get no sound when attempting to stream any non-steam game added to the Steam interface unless it's an exe being ran through Proton. So in this case, flatpak apps don't have any sound when streamed.

**Comment by kcs-web** [comment]
I was able to work around this by reverting the Steam client back to before the "game recording" update.

Here is a reference on how to download the Steam client.

https://steamcommunity.com/discussions/forum/0/6516193260168294059/?ctp=62&_x_tr_sl%5B%5D=auto&_x_tr_sl%5B%5D=auto&_x_tr_sl%5B%5D=auto&_x_tr_sl%5B%5D=auto&_x_tr_tl%5B%5D=ja&_x_tr_tl%5B%5D=ja&_x_tr_tl%5B%5D=ja&_x_tr_tl%5B%5D=ja&_x_tr_hl%5B%5D=ja&_x_tr_hl%5B%5D=ja&_x_tr_hl%5B%5D=ja&_x_tr_hl%5B%5D=ja#c3875967149487755456

However, the downgrade shortcut options are different.
The following options will allow you to download the version just before the “Game Recording Update”.

 -forcesteamupdate -forcepackagedownload -overridepackageurl https://web.archive.org/web/20240918104445if_/media.steampowered.com/client -exitsteam

“STAGE THREE:” 2. and after are not required.
This is a procedure to enable the friend list for old Steam clients.
