### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by KaiserCalm** [m4dEngi/RemotePlayWhatever#24]
It seems to not work again both for me on Linux Pop!_OS 21.04 and my friend on Windows 10. Clicking Create Link does not do anything.

**Comment by m4dEngi** [comment]
Works fine for me with latest stable client on W10.

**Comment by m4dEngi** [comment]
Make sure you're using latest RPW version with latest stable steam client.

**Comment by KaiserCalm** [comment]
Thanks! Being on the beta was the issue.
