### ISSUE TITLE
when my friend joins, there is no audio. and when my friend joins by invite, it only shows a black screen

### ISSUE THREAD

**Issue by Detrussky** [m4dEngi/RemotePlayWhatever#25]
so me and my friend wanted to play a game together, everything works great, but when he joins by guest he doesn't hear the audio of the game.

when he tries to join by invite, because usually the invite will send a link to that user in message but he didn't get it.

so when he joined by going to me and press join game, it shows a pitch black screen,

please fix it.

**Comment by m4dEngi** [comment]
That's not a RPW issue. You should probably report it to Valve somewhere here: https://steamcommunity.com/groups/homestream/discussions
