### ISSUE TITLE
Unable to send invite

### ISSUE THREAD

**Issue by Canpake59** [m4dEngi/RemotePlayWhatever#34]
Hello. I am trying to use the program on a non steam game, so I launch the program, then I launch the game through steam as a non steam game (I have steam overlay) and when I alt tab to click on the remoteplaywhatever program in the system tray nothing happens, no invite, no popup, nothing. How do I fix this?

**Comment by m4dEngi** [comment]
Current version does not support latest steam client. I'm working on update.

**Comment by Canpake59** [comment]
> 

Sounds great. Thanks for the reply and eagerly waiting for the update! 👍
