### ISSUE TITLE
links expired instantly. 

### ISSUE THREAD

**Issue by danielphingston** [m4dEngi/RemotePlayWhatever#38]
![image](https://user-images.githubusercontent.com/18254184/151131248-ecf4d646-def7-4f38-b80c-54f24effa038.png)
maybe steam fixed it?

**Comment by spartanatreyu** [comment]
Yeah, getting the same

**Comment by m4dEngi** [comment]
Not sure about this. Could be true, but i just tried with the game that supports RPT with the same result.

**Comment by m4dEngi** [comment]
https://steamcommunity.com/groups/homestream/discussions/0/3192490990763215831/ looks like an issue with steam backend.

**Comment by danielphingston** [comment]
> https://steamcommunity.com/groups/homestream/discussions/0/3192490990763215831/ looks like an issue with steam backend.

oh... i should have checked this before posting. sorry. anyways thanks for the update.
