### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by lannahirave** [m4dEngi/RemotePlayWhatever#39]
Says that invitation expired.

**Comment by laissaassi** [comment]
yeah I'm having the same issues

**Comment by m4dEngi** [comment]
https://github.com/m4dEngi/RemotePlayWhatever/issues/38 looks like it's broken at steams end even for supported titles.

**Comment by Mkwilsonmusic** [comment]
When opening the app it now says - "OpenSteamAPI.dll"missing from computer. 

The app was working last night, just want to also say what a game changer this has been for playing games with brother long distance. Thanks for whoever made this!
