### ISSUE TITLE
App quits if user has exactly one friend

### ISSUE THREAD

**Issue by Ivasha77** [m4dEngi/RemotePlayWhatever#4]
If a steam user has only one friend, the app correctly creates menu with single menu item for that user. However, when 'Send invite' menu item for that user is clicked, then app cleanly quits instead of creating the invite.

**Comment by m4dEngi** [comment]
Bug was cause by incorrect event binding. Thought i could get away with it... https://github.com/m4dEngi/RemotePlayWhatever/commit/355269526c214d9fe671d10dc4fbf2ef576917c5
Latest release should fix the problem.
