### ISSUE TITLE
Steam Update broke program

### ISSUE THREAD

**Issue by Ianhanley** [m4dEngi/RemotePlayWhatever#44]
It was working perfectly on Tuesday, but after the new Steam update, which included Remote Play bug fixes, the program closes without a message when attempting to either send a Remote Play Together invite, or create a RPT link.

**Comment by georgefst** [comment]
I'm finding that the program doesn't close, but my friends never receive a message when I use `Send remote play invite to...`. This is the first time I've tried to use RemotePlayWhatever though, so my issue _could_ be unrelated.

Latest version, Manjaro Linux.

**Comment by m4dEngi** [comment]
Working on it. Will try to push an update today if it's still possible.

**Comment by georgefst** [comment]
Thanks.

I'm confused though. Is this fixed? I see there's a new release, but there are no actual changes on `master`.

**Comment by m4dEngi** [comment]
All changes are on OpenSteamworks lib. There's nothing to be changed here aside from version number.

**Comment by georgefst** [comment]
Okay, great. I'm so used to pinning dependencies that I didn't even consider that.

**Comment by m4dEngi** [comment]
Some day i'll make things better, but now i'm just too lazy to refactor OSW.
