### ISSUE TITLE
Unclear what `Create remote play invite link` is supposed to do

### ISSUE THREAD

**Issue by georgefst** [m4dEngi/RemotePlayWhatever#45]
It probably doesn't help that nothing is working for me at the moment (https://github.com/m4dEngi/RemotePlayWhatever/issues/44#issuecomment-1059739755), but the `Create remote play invite link` button could do with some documentation. Is it supposed to copy something to the clipboard, open a new UI, ...?

**Comment by m4dEngi** [comment]
It's unclear mostly because in it's current state app is broken.

**Comment by georgefst** [comment]
Not an issue with 0.1.14. Behaviour is obvious when the app actually works.
