### ISSUE TITLE
Bug with the latest update

### ISSUE THREAD

**Issue by Mollinho** [m4dEngi/RemotePlayWhatever#46]
So when i´m inviting a friend. The friend see the game like 100% brighter then normal.

**Comment by m4dEngi** [comment]
I'm afraid i can't help you with it. It looks more like an issue with Steam Remote Play Together rather than issue with RPW.

**Comment by Mollinho** [comment]
Oh okay but do you have any clue what I can do?

**Comment by m4dEngi** [comment]
I have no idea if it's possible to do anything. Remote Play is tied to steam in-game overlay, there's not that much we can do as far as i know. Some games have remote play disabled for a reason.
