### ISSUE TITLE
Appears to be broken with latest steam

### ISSUE THREAD

**Issue by Justsnoopy30** [m4dEngi/RemotePlayWhatever#48]
No window opens when clicking "Create remote play invite link"

**Comment by m4dEngi** [comment]
Seems to work fine with latest stable client. Make sure that you're on latest stable client and remote play is enabled in client settings.

**Comment by Justsnoopy30** [comment]
I have checked both those things, no such luck for mue. Running Ubuntu 22.04.

**Comment by Justsnoopy30** [comment]
After reinstalling I seem to be able to create the invite window, but now the remote player gets stuck at "please hold input is temporarily disabled while the host is busy." The game in question being streamed is Doom Eternal.

**Comment by resolutedreamer** [comment]
<img width="257" alt="image" src="https://user-images.githubusercontent.com/3419924/166865197-46492808-cbe9-4728-b046-c7cfd9befd51.png">

**Comment by m4dEngi** [comment]
Beta client isn't supported atm.

**Comment by resolutedreamer** [comment]
Thank you very much, I didn't even know I was using Beta. I changed it back and it works.

**Comment by Mandukee** [comment]
> Thank you very much, I didn't even know I was using Beta. I changed it back and it works.

hello, if i may ask how to revert my steam client to it's previous version ? 
i have the same issue

**Comment by resolutedreamer** [comment]
> > Thank you very much, I didn't even know I was using Beta. I changed it back and it works.
> 
> hello, if i may ask how to revert my steam client to it's previous version ? i have the same issue

![image](https://user-images.githubusercontent.com/3419924/172076403-7432a674-8731-4231-b0a6-945480a0e46b.png)
