### ISSUE TITLE
Friend gets white screen when the game window is selected. 

### ISSUE THREAD

**Issue by SpaceGhost97** [m4dEngi/RemotePlayWhatever#49]
When my friend joins the invite they only see a white screen when the game window is selected. When the game window is not selected they can see it. 

Ive tried windowed and fullscreen setting for the game, nothing changes. Any advice? Thx!

(LEGO StarWars Skywalker Saga)(Non-Steam)

**Comment by Dr-Corn** [comment]
Yeah I'm having the same issue here

**Comment by m4dEngi** [comment]
Sorry, i don't think i can help you with that. That's an issue with Steam In-game Overlay and Remote Play Together. There's nothing that can be done about it that's in the scope of this project.
