### ISSUE TITLE
App crashes (quits?) when inviting friend to game

### ISSUE THREAD

**Issue by JustArchi** [m4dEngi/RemotePlayWhatever#5]
I've tried to test latest release (0.1.6) with Slay the Spire, a game where remote play works if launched as other game with remote play enabled. Unfortunately the app crashes/exits when sending the invite, and Steam displays an error about sending an invite claiming it's unable to start session because of that.

Is there any way I can provide some debug info to help you analyze the case? Debugging myself with NetHook2 I can see a call to `RemoteClient.AllocateSDR#1` with payload of integer `353380` and the response with `eresult` of `1` (OK), but no communication afterwards.

Thank you in advance for looking into that.

**Comment by m4dEngi** [comment]
Are you on beta client branch? 
If it's beta, then latest beta client changed callbacks layout adding extra field(s) and slightly changed function signatures in  IClientRemoteClientManager causing app to crash due to stack corruption.

**Comment by JustArchi** [comment]
Yes, I'm on beta branch, that would explain the problem then, thank you for responding.

Would you be so kind to prepare v0.2.0 release (or anything) fixed for latest beta branch of Steam client? I guess those changes will land in stable sooner or later, the release info could state that it's for latest beta of the client.

Thanks again!

**Comment by m4dEngi** [comment]
Sorry, i have no plans to support beta client at the moment.

**Comment by JustArchi** [comment]
That's understandable, thanks a lot for the help regardless! 🙂
