### ISSUE TITLE
It doesn't work.

### ISSUE THREAD

**Issue by kriki200** [m4dEngi/RemotePlayWhatever#53]
I don't have any new buttons.

**Comment by m4dEngi** [comment]
Could use more details about the issue. What's your OS? What's your steam client version? What behavior did you expect from app?

**Comment by kriki200** [comment]
Windows 11, was on the previous stable version, some new button when alt-tabbing.

**Comment by Lolipop2511** [comment]
stopped working

**Comment by Fesiug** [comment]
I'm on Manjaro Linux. Inviting a friend doesn't send or do anything, and creating a link doesn't copy or show anything. I'm on the latest stable of Steam.
![image](https://user-images.githubusercontent.com/40924091/173217074-11ad54bf-b37b-4072-acbb-5116a74a15bb.png)

**Comment by Ihmoda** [comment]
Also having issues on the Steam Deck in Desktop mode. On stable channels.

![about steam](https://user-images.githubusercontent.com/25795176/175220267-a02893e8-fe1a-418b-9480-f47fb3643bef.png)

**Comment by m4dEngi** [comment]
Ah, that explains. Latest stable linux build is from Jun 7th.

**Comment by OParczyk** [comment]
Is there any ETA as to when you might get around to look into this issue?

**Comment by OParczyk** [comment]
The issue is the same for me on the Jun 7th client (API v020, Steam- package versions 1654574690)
It did work before on the latest release, but while the options are present to create or send invites, they don't do anything now.
`--verbose` doesnt generate any output when trying to create an invite link (and have it not work)

Is there any ETA as to when you might get around to look into this issue?

**Comment by OParczyk** [comment]
Very interesting - I've built the application myself and it seems to have fixed it

**Comment by OParczyk** [comment]
Today there was a steam update (Jul 26 2022, at 18:54:18, v020, 1658944613) and rebuilding didn't seem fix it this time, sadly

**Comment by m4dEngi** [comment]
I'm not a git power user, but maybe you can try updating project submodules with ``git pull --recurse-submodules`` before rebuilding.

**Comment by OParczyk** [comment]
Of course, totally forgot that - and indeed that fixed it, thank you very much!
