### ISSUE TITLE
App crashes when inviting friend to game

### ISSUE THREAD

**Issue by ddmxm** [m4dEngi/RemotePlayWhatever#61]
The program crashes immediately after inviting a friend to Steam. This is probably due to the steam client update that happened 2 days ago.

Steam - version from 07/26/2022; 
steamapi - v020;
steam version - 1658944613;

Windows 11 21H2;

**Comment by Zombeaver** [comment]
Same issue here, it stopped working after the last Steam client update. W10 in my case.

**Comment by m4dEngi** [comment]
Should be fixed with latest release.

**Comment by ddmxm** [comment]
Yes, it works with the new version.  Thank you!
