### ISSUE TITLE
non-steam games don't have controller compatibility

### ISSUE THREAD

**Issue by Junins** [m4dEngi/RemotePlayWhatever#62]
I added the ps3 emulator to steam and tried to play with a friend but I can't activate his controller
maybe changing the nonsteamapp from Spacewar to Retroarch can fix this
![Screenshot_1](https://user-images.githubusercontent.com/63080380/182297418-0f095368-3cd0-49d7-8d9b-258f47e88ab0.png)

**Comment by m4dEngi** [comment]
#7
