### ISSUE TITLE
Not working after new Steam update

### ISSUE THREAD

**Issue by Mkwilsonmusic** [m4dEngi/RemotePlayWhatever#66]
I can't use the interface after the new steam update. It's just not working.

Also want to say thanks to the devs, really amazing project.

**Comment by SilentBronyRain** [comment]
It refuses to launch completely now, but i still get error while launching without steam

**Comment by poleselalex** [comment]
does not launch after new steam update

**Comment by chevchungus** [comment]
frick man i only want toplay oiblivion 2!!!

**Comment by m4dEngi** [comment]
Should be fixed with latest release.
