### ISSUE TITLE
Support Inviting up to 3 people from CLI

### ISSUE THREAD

**Issue by joamjoamjoam** [m4dEngi/RemotePlayWhatever#71]
Im working on the Decky plugin and founds that while calling the CLI once per invite works, it doesn't keep the Steam UI Updated with people invited. Is it possible to update the -i or add a new param to allow a comma separated list of IDs to send invites to (up to 3)?

**Comment by joamjoamjoam** [comment]
After a little bit more testing if you send a second invite via cli it will cause the forst link to expire. Meaning you csn only have one active link at a time with the current implementation

**Comment by m4dEngi** [comment]
Guess that's because of remote client id being reset on each run. I'll add a new param for initial client id in next release.

**Comment by joamjoamjoam** [comment]
Sweet Thanks!

**Comment by m4dEngi** [comment]
Uploaded a new version with added batch invites, guestid via arg and invitation cancellations ( one at time, and steam own UI will remain, even when invitation is successfully cancelled, because whatever we do is undefined behavior for steamui).

**Comment by joamjoamjoam** [comment]
Tested with my decky plugin and i can invite 3 people to a session. Good work and Thanks!
