### ISSUE TITLE
9/22  steam deck stable update beaks RPW

### ISSUE THREAD

**Issue by joamjoamjoam** [m4dEngi/RemotePlayWhatever#77]
New steam deck update on the stable channel breaks RPW.

**Comment by joamjoamjoam** [comment]
With decky loader the steam deck has access to the steam client functions. Is it possible to detail how you perform the switcheroo to get non steam games working? Preferably which api calls are used?

**Comment by m4dEngi** [comment]
https://github.com/m4dEngi/RemotePlayWhatever/blob/67b1a4344ac46fbb978ad79eeedb966c3c1d6746/RemotePlayWhatever/RemotePlayInviteHandler.cpp#L29 you could just check the code...

These functions are not exported to cef context as is last time i checked.

**Comment by joamjoamjoam** [comment]
I believe that one is. And that will show the rpt tab but yiu can send invited from it. It just does nothing when you try. I see that that you send the invites via steam chat apis with links. Where dp you get the links from?

Basically everything makes sense except for the invite handler part. Should i have to register a callback for an accepted invite or would the steam client handle that on its own if i figure out how to send the invite to the session?

**Comment by m4dEngi** [comment]
I have no idea what are you trying to do and how, but yes, steam client will post callback with start session result.

https://github.com/m4dEngi/open-steamworks/blob/581ae4792a5d9fce65dbe80ce1b340dfac055edc/OpenSteamworks/Types/RemoteClientCommon.h#L147

**Comment by joamjoamjoam** [comment]
Gotcha. Im trying to use the internal steam client exposed via react/JS to replicate RPW so it wouldnt break on each client update. Is it worth the effort in your opinion to jump down that rabbit hole or is it easier to work on open steam works?

You definitley have more knowledge than i do about how this works so if you say theres some internal api calls not available via cef than i believe you lol. 

The decky plugin i wrote uses the RPW app image so i dont mind just waiting patiently for the new one. If i can help minimize the workload let me know.
