### ISSUE TITLE
Last stable update broke invite creation

### ISSUE THREAD

**Issue by OParczyk** [m4dEngi/RemotePlayWhatever#79]
Probably related to #77 .
Whenever I try to create an invite link, RPW crashes at

RemotePlayWhatever/RemotePlayWhatever/RemotePlayInviteHandler.cpp:92
`GClientContext()->RemoteClientManager()->CreateRemotePlayInviteAndSession(rppInvitee, gameID.AppID())`
with `pure virtual method called` at/in steamclient.so. 

I tried to get my hands dirty and finally understand how you know how to do your updates, but I only came as far as to use your steamworks_dumper and diffing against https://github.com/SteamDatabase/SteamTracking/tree/master/Structs sort of pre-last-update (in lack of an pre-update steamclient.so)
While a few definitions in some Interfaces were added and one removed, translating these changes into your OSW fork did not change the current behavior.

Do you have any resources for me on how one could get up to speed with (the parts of) this project and the related workflow?
(And take a look into the issue ;))

I greatly appreciate this project and would love to be able to fix it on update myself, too.

**Comment by joamjoamjoam** [comment]
I have the same sentiment as OP. Im willing to help whereever i can.

**Comment by matheusfaustino** [comment]
I also have a deck and can help figure out what is happening and try to fix it as well, together.

**Comment by OParczyk** [comment]
To be clear, this Issue is not SteamDeck-specific and since I don't have one (yet), I can't even confirm for it to manifest "not working" exactly the same way. I'm on a regular desktop, Ubuntu 22.04

**Comment by m4dEngi** [comment]
> I tried to get my hands dirty and finally understand how you know how to do your updates, but I only came as far as to use your steamworks_dumper and diffing against https://github.com/SteamDatabase/SteamTracking/tree/master/Structs sort of pre-last-update (in lack of an pre-update steamclient.so) While a few definitions in some Interfaces were added and one removed, translating these changes into your OSW fork did not change the current behavior.
> 
> Do you have any resources for me on how one could get up to speed with (the parts of) this project and the related workflow? (And take a look into the issue ;))
> 
> I greatly appreciate this project and would love to be able to fix it on update myself, too.

steamworks_dumper currently doesn't dump IClientEngine interface/factory, i do it manually whenever new interface is added. ( If you're interested how it's done i can explain the whole process later )
Latest steam client introduced new client interface that broke RPW. I'll try to update OSW and fix RPW asap.

**Comment by OParczyk** [comment]
Thank you very much!
I'm indeed very interested in the process and would greatly appreciate for you to share your insights.

**Comment by MrHomebrew** [comment]
Would definitely give this a test run when it is up and running again

**Comment by staticnation** [comment]
```$ ./Remote*.AppImage
Gtk-Message: 22:41:25.808: Failed to load module "canberra-gtk-module"
Unexpected parameter './RemotePlayWhatever-0.2.0-x86_64.AppImage'
Usage: remoteplaywhatever [-h] [-v] [-a <num>] [-i <str>]
  -h, --help            show this help message
  -v, --verbose         verbose output
  -a, --appid=<num>     AppID for non-steam games
  -i, --invitee=<str>   SteamID64 invitee ( use 0 for guest link )
Gtk-Message: 22:41:26.671: Failed to load module "colorreload-gtk-module"
Gtk-Message: 22:41:26.674: Failed to load module "window-decorations-gtk-module"```

**Comment by extract** [comment]
@m4dEngi Any update on this? :)

**Comment by OParczyk** [comment]
> steamworks_dumper currently doesn't dump IClientEngine interface/factory, i do it manually whenever new interface is added. ( If you're interested how it's done i can explain the whole process later ) Latest steam client introduced new client interface that broke RPW. I'll try to update OSW and fix RPW asap.

Thank you very much for fixing the issue! While for whatever reason my own build doesn't do anything after confirming invite creation, the AppImage works fine.

Could you please document your process as offered?
Thanks again!

**Comment by m4dEngi** [comment]
> Could you please document your process as offered? Thanks again!
Sure. But a little bit later and it'll probably be [here](https://github.com/m4dEngi/steamworks_dumper), since it's outside of scope of RPW project.
