### ISSUE TITLE
After Steam update RemotePlayWhatever doesn't work

### ISSUE THREAD

**Issue by EkT1oN** [m4dEngi/RemotePlayWhatever#81]
Client Steam
Build from 16 November 2022
Steam API: v020
Version Steam package: 1668654564

I think Steam change something in API

**Comment by Chabudds** [comment]
> Client Steam Build from 16 November 2022 Steam API: v020 Version Steam package: 1668654564
> 
> I think Steam change something in API

Yeah, I have the same issue the app won't launch since the steam update.

**Comment by BALABOLNITSA** [comment]
+1

**Comment by MarcoBarakadi** [comment]
+1

**Comment by Skyro468** [comment]
+2 Also not working here.

**Comment by m4dEngi** [comment]
Working on it. Might take some to update OSW.

**Comment by sel4ik** [comment]
How much longer to wait?

**Comment by Merudo** [comment]
> How much longer to wait?

You can open a pull request if you have a fix to share.

**Comment by sleeksorrow** [comment]
Tag 0.2.1-pre-alpha works for me! Thank you very much!
