### ISSUE TITLE
The link is sent with a delay and my friend can't connect to it

### ISSUE THREAD

**Issue by dannyr23** [m4dEngi/RemotePlayWhatever#89]
This problem occurred today, when I tried sending the invitation the usual way to my friend it

1. Took more than usual to send out the link (takes around 30-40 sec)
2. Was invalid for my friend (doesn't connect my friend to remote play)

Never experienced this before, tried restarting PC, router, RPW and the game.

**Comment by Zombeaver** [comment]
I'm having this today as well. I'm not 100% certain that this is a RPW issue and not just a Steam issue though.

**Comment by andOlga** [comment]
Something's going on on Steam's end since normal RPT links don't work either.
