### ISSUE TITLE
worked earlier today, now doesn't work at all.

### ISSUE THREAD

**Issue by ZeroGeeEnn** [m4dEngi/RemotePlayWhatever#93]
Started using this today, managed to get it to work perfectly fine, even after todays 10am update. Played for about 2 hours with a friend. Closed everything, did not restart pc. 7 hours later, tried to play with another friend, would crash the second I clicked name to send invite, or tried to copy.  Uninstalled and reinstalled everything, now program doesn't open at all.

**Comment by Trolot** [comment]
Stopped working for me as well. 
The program can't send invites or generate invite links anymore, the Remote Play Together UI does start up however.

**Comment by Phobobobo** [comment]
Stoped working for me too. I think this needs to be updated.

**Comment by RadikAlice** [comment]
Has been an issue for me since at least January 31st
Doesn't launch for me, however, the warning when doing it without Steam open does display
I'm pretty confident app itself works, but some Steam update broke it. Intentionally or not

**Comment by m4dEngi** [comment]
Should be fixed with latest release

**Comment by RadikAlice** [comment]
Just tried it, does open. I assume it does work correctly too
But got nobody to test it with. Anyway, thank you so much!

**Comment by Trolot** [comment]
The program does open but you can't invite anyone or create an invite link

**Comment by HutchMD** [comment]
I know this issue is closed, but I am unable to create an invite link.
The UI crashes after trying to create a guest invite link.

Not sure if there's a way for me to send logs or anything like that to help?

**Comment by m4dEngi** [comment]
Make sure you're using latest stable client.

**Comment by HutchMD** [comment]
Restarting Steam to force an update didn't work, however.... restarting my computer _twice_ did...
Weird. Thanks for all your work!
