### ISSUE TITLE
Latest steam update breaks the app.

### ISSUE THREAD

**Issue by adabo** [m4dEngi/RemotePlayWhatever#95]
Steam just updated yesterday and now it seems the app just crashes whenever an invite is sent. Does this happen to anyone else?

**Comment by dotkeenan** [comment]
yup shits broken.

**Comment by DriftWare07** [comment]
Yeah it won't detect any games

**Comment by DriftWare07** [comment]
Hope this gets fixed

**Comment by adabo** [comment]
It seems the issue has indeed returned.

**Comment by m4dEngi** [comment]
Looks fine on my end. Tested with latest stable client on win7/linux. 


> Yeah it won't detect any games 

You need to be signed in to friends & chat and have an online in-game status.
